[Distribution]
Distribution=arch
Architecture=x86-64

[Output]
Format=disk
Bootable=yes
Output=arch.raw
RootKeyFiles=root.key
SecureBootKey=mkosi.extra/var/lib/sbctl/keys/db/db.key
SecureBootCertificate=mkosi.extra/var/lib/sbctl/keys/db/db.pem
ImageId=arch
# You can pass this version dynamically via command line when running mkosi
ImageVersion=2026.06.18

[Content]
Bootloader=systemd-boot
KernelCommandLine=rw splash quiet

Packages=
    base
    base-devel
    linux
    linux-firmware
    amd-ucode
    systemd
    systemd-ukify
    sbctl
    dracut
    btrfs-progs
    cryptsetup
    plymouth
    pipewire-jack
    wireplumber
    xdg-desktop-portal-kde
    qt6-multimedia-ffmpeg
    xorg-xwayland
    vulkan-tools
    mesa
    lib32-mesa
    vulkan-radeon
    lib32-vulkan-radeon
    linux-firmware-amdgpu
    steam
    flatpak
    sddm
    plasma-meta

[Services]
EnabledServices=
    systemd-homed.service
    systemd-resolved.service
    systemd-networkd.service
    systemd-oomd.service
    fstrim.timer
    sddm.service
    firstboot-homed.service
    firstboot-pcrlock.service
    firstboot-secureboot.service
